### ISSUE TITLE
Service is started before canable interface is up

### ISSUE THREAD

**Issue by ostroesser** [openplotter/openplotter-can#5]
When starting up the Pi, the can read service fails to initialize correctly as the canable0 interface is not up yet (at least 9 times out of 10 for me):

```openplotter-can-read.service
     Loaded: loaded (/etc/systemd/system/openplotter-can-read.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-02-03 05:16:22 GMT; 1min 35s ago
   Main PID: 429 (openplotter-can)
      Tasks: 2 (limit: 3954)
        CPU: 1.352s
     CGroup: /system.slice/openplotter-can-read.service
             └─429 /usr/bin/python3 /usr/bin/openplotter-can-read

Feb 03 05:16:22 openplotter systemd[1]: Started openplotter-can-read.service.
Feb 03 05:16:25 openplotter slcand[711]: starting on TTY device /dev/ttyOP_can
Feb 03 05:16:25 openplotter slcand[711]: failed to open TTY device /dev/ttyOP_can
Feb 03 05:16:25 openplotter openplotter-can-read[711]: /dev/ttyOP_can: No such file or directory
Feb 03 05:16:26 openplotter openplotter-can-read[792]: Cannot find device "canable0"
```

The problem can be fixed by adding a delay in the ExecStart directive
```
[Service]
ExecStartPre=/bin/sleep 10
...
```
Probably someone who knows systemd can come up with a elegant solution

**Comment by sailoog** [comment]
thanks for reporting, I will try to reproduce and fix the issue.
Maybe the best way is adding the pause in the service itself: https://github.com/openplotter/openplotter-can/blob/master/openplotterCan/openplotterCanRead.py

Actually, I think there is another non-critical issue there. The last loop keeps the script running and once it has done its job, we do not need it.

**Comment by sailoog** [comment]
It should be fixed in v3.2.21, try removing your ExecStartPre and report please.

I have added a loop in the service to check and wait 5 seconds to check again, after 5 attempts it tries another device or exits. 

Forget my comment about the last loop, I forgot that systemctl kills all the subprocess by default when the main process stops. Keeping the main process alive is better than keep orphan processes.

**Comment by ostroesser** [comment]
Can confirn V3.2.21 seems to fix the issue

**Comment by sailoog** [comment]
Perfect, thanks for reporting.
